version: '2'
volumes:
  postgresql:
    external: true

services:
  #  lampaderum-node:
  #    image: lampaderum_frontend
  #    build:
  #      context: .
  #      dockerfile: lampaderum-prod-nginx-angular.dockerfile
  #    ports:
  #      - 80:80
  #    volumes:
  #    - ../../../nginx.conf:/etc/nginx/conf.d/default.conf
  #    depends_on:
  #      - 'lampaderum-app'

  lampaderum-app:
    image: jalaimo/lampaderum:0.0.1-SNAPSHOT_recette
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lampaderum-postgresql:5432/Lampaderum
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    privileged: true
    ports:
      - '80:8080'
    depends_on:
      - 'lampaderum-postgresql'
      - 'jhipster-registry'

  lampaderum-postgresql:
    extends:
      file: postgresql.yml
      service: lampaderum-postgresql
    volumes:
      - /opt/postgre/data/:/var/lib/postgresql/data/

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
